name: Sync Main to Release

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Checkout Release Branch
      run: |
        git fetch origin release
        git checkout release

    - name: Merge Main into Release
      run: |
        git merge main --no-edit

    - name: Push to Release Branch
      run: |
        git push origin release
