name: kyle-action

on:
  push:
    branches: [ kyle-cicd ]

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build-kyle-staging
      - name: SCP bundle to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.KYLE_STAGING_HOST }}
          username: ${{ secrets.KYLE_STAGING_USERNAME }}
          key: ${{ secrets.KYLE_STAGING_KEY }}
          source: "./dist"
          target: ${{ secrets.KYLE_PENGUIN_CLIENT_DEPLOY_DIRECTORY }}
