name: Sync Main to Release

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Token and Permissions
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          echo "Token length: ${#BOT_TOKEN}"
          
          curl -s -H "Authorization: token $BOT_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user \
               | jq -r '.login, .permissions'
      
      - name: Checkout with Debug
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          
      - name: Test Repository Access
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Testing access to $REPO"
          curl -s -H "Authorization: token $BOT_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$REPO" \
               | jq -r '.permissions'
