name: Update Release Branch

on:
  workflow_dispatch:
    inputs:
      target_commit:
        description: 'Commit hash to set release branch to (defaults to main)'
        required: false
        default: 'main'

jobs:
  update_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Update Release Branch
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_PAT }}
        run: |
          # Configure git
          git config --global user.name "Devature Bot"
          git config --global user.email "bot@devature.dev"
          
          # Remove and re-add origin with token
          git remote remove origin
          git remote add origin "https://x-access-token:${ADMIN_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          
          # Verify remote
          echo "Remote URL (token masked):"
          git remote -v | sed 's/x-access-token:[^@]*@/***@/'
          
          # Fetch all branches
          git fetch origin
          
          # Get target commit
          TARGET_COMMIT="${{ github.event.inputs.target_commit }}"
          if [ "$TARGET_COMMIT" = "main" ]; then
            echo "Using main branch HEAD"
            TARGET_COMMIT=$(git rev-parse origin/main)
          fi
          echo "Target commit: $TARGET_COMMIT"
          
          # Create/update release branch
          echo "Creating/updating release branch..."
          git checkout -B release $TARGET_COMMIT
          
          # Force push
          echo "Force pushing to release branch..."
          git push -f origin release
