name: Sync Main to Release

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Safe Directory
        run: |
          git config --global --add safe.directory '*'
          
      - name: Clone and Setup
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          git clone "https://$BOT_TOKEN@github.com/$REPO.git" .
          
          git config user.name "Devature Actions"
          git config user.email "bot@devature.dev"
          
          git fetch --all
          git fetch origin main:main
          
          git checkout release 2>/dev/null || git checkout -b release
          
          git reset --hard origin/main
          
          git push -f "https://$BOT_TOKEN@github.com/$REPO.git" release
