name: Update Release Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Devature/penguin-client
          token: ${{ secrets.REPO_PAT }}
          fetch-depth: 0
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-tags: false
          show-progress: true
          lfs: false
          submodules: false
          set-safe-directory: true
          
      - name: Configure Git
        run: |
          git config --global user.name "Devature Actions"
          git config --global user.email "bot@devature.dev"
          
      - name: Update Release Branch
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/Devature/penguin-client.git

          git fetch origin
          
          if ! git show-ref --quiet refs/remotes/origin/release; then
            git checkout -b release
          else
            git checkout release
          fi
          
          git reset --hard origin/main
          
          git push --force origin release
          
