name: Update Release Branch

on:
  workflow_dispatch:
    inputs:
      target_commit:
        description: 'Commit hash to set release branch to (defaults to main)'
        required: false
        default: 'main'

jobs:
  update_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_PAT }}
          
      - name: Debug Permissions
        run: |
          echo "Current user:"
          git config --get user.name || echo "user.name not set"
          git config --get user.email || echo "user.email not set"
          echo "Remote URL:"
          git remote -v
          echo "Current branch:"
          git branch --show-current
          
      - name: Update Release Branch
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}
        run: |
          # Explicitly set git config
          git config --global user.name "devature-actions[bot]"
          git config --global user.email "devature-actions[bot]@users.noreply.github.com"
          
          # Print git config for verification
          echo "Git config after update:"
          git config --list
          
          # Get and verify target commit
          TARGET_COMMIT="${{ github.event.inputs.target_commit }}"
          if [ "$TARGET_COMMIT" = "main" ]; then
            echo "Using main branch HEAD"
            TARGET_COMMIT=$(git rev-parse origin/main)
          fi
          echo "Target commit: $TARGET_COMMIT"
          
          # Verify the commit exists
          if ! git cat-file -e $TARGET_COMMIT^{commit}; then
            echo "Error: Invalid commit hash"
            exit 1
          fi
          
          # Create/update release branch
          echo "Creating/updating release branch..."
          git checkout -B release $TARGET_COMMIT
          
          # Force push with lease for safety
          echo "Pushing to release branch..."
          git push --force-with-lease origin release || {
            echo "Force with lease failed, attempting direct force push..."
            git push -f origin release
          }
