name: Update Release Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_PAT }}
          
      - name: Configure Bot Git User
        run: |
          git config --global user.name "Devature Actions"
          git config --global user.email "bot@devature.dev"
          
      - name: Update Release Branch
        run: |
          # Fetch latest changes from remote
          git fetch origin
          
          # Check if release branch exists, create if it doesn't
          if ! git show-ref --quiet refs/remotes/origin/release; then
            git checkout -b release
          else
            git checkout release
          fi
          
          # Reset release branch to match main
          git reset --hard origin/main
          
          # Force push to release branch using bot's token
          git push --force origin release
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PAT }}
