name: Sync Main to Release

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
          
      - name: Configure Git
        run: |
          git config user.name "Devature Actions"
          git config user.email "bot@devature.dev"
          
      - name: Sync Branches
        run: |
          git fetch origin
          
          if git show-ref --quiet refs/remotes/origin/release; then
            git checkout release
            git pull origin release
            
            if ! git merge main --allow-unrelated-histories --no-edit; then
              git merge --abort
              git reset --hard origin/main
            fi
          else
            git checkout -b release
          fi
          
          git push -f origin release
